name: "github actions build and deploy gh-pages" #流程名称
on:
  push:
    branches: [ main ]  #当对当前仓库push代码的时候触发
jobs:
  build-and-deploy: #脚本名称
    runs-on: ubuntu-latest #运行在乌班图linux上
    steps:
      - name: Checkout #步骤1：checkout
        uses: actions/checkout@v4 #checkout需要引用的依赖
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: "pnpm"
      # - name: install and build #步骤2：安装依赖和打包
      - run: pnpm install #安装依赖，当前分支的根目录做为默认目录
      - run: pnpm run build #打包代码

      # - run: cp -rp icons ./dist
      # - run: |
      - run: ls -lth
      - run: find ./ -iname "*.html*" -type f
      # - run: cd dist
      # - run: zip -r ../dist.zip ./*

      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifacts
      #     path: dist.zip
